### ISSUE TITLE
cannot find metacell_annotation_kill

### ISSUE THREAD

**Issue by bettycatherine** [sebepedroslab/Stylophora_single_cell_atlas#1]
Thank you for this amazing work. I am repeating your analysis, however, I noticed there is a crucial file which I cannot locate in any of the folders, the "Metacell_annotation_kill" file, and presumably helped to annotate cell types for metacells. It will be highly appreciated if you can apply this file. Thank you very much!

Best,
Betty

**Comment by anamariaelek** [comment]
Hi Betty,

indeed, this intermediate file is missing from git, as it changed with different clustering solution we tried, and with different annotation solutions, sorry about that.
You can, however, easily generate this starting point for annotation of your clustering solution from the final cell annotations, like this:

```
require(metacell)
require(data.table)

# load your current metacell object and annotation files
mc <- scdb_mc("mc_k30")
dt <- fread("clustering_coral/scdb/Spis_coral_cell_type_assignments")
ctann <- fread("clustering_coral/scdb/Spis_coral_cell_type_annotation")[,2:3]

dt <- dt[match(names(mc@mc),cell),][             # match cells in current metacell solution to cell type annotation
  ,metacell:=mc@mc][                             # add current metacell numbers 
    is.na(cell),cell_type:="KILL"][              # killed cells will be missing in final annotation
      ,.N,.(cell_type,metacell)][                # sum cells per metacell and cell type
        order(metacell,N)][,.SD[1],metacell][    # select majority-voting annotation for metacell
          ,N:=NULL]                              # remove N column
dt <- merge.data.table(dt,ctann,on="cell_type")  # add colors

# this is the file you need
fwrite(dt, "clustering_coral/scdb/Metacell_annotation_kill", sep="\t", col.names=TRUE)
```

Sorry for the inconvenience!

Anamaria

**Comment by bettycatherine** [comment]
Thank you @anamariaelek very much for your reply. I have one more question is about the function of **sca_cell_type_fp**
which you used to calculate footprint based on cell types, and I could not find detail about this code anywhere in this git. So would you please share this function, is this from any package or developed by yourself?

```
# calculate mc object with mc_fp by cell type
mc_ct <- sca_cell_type_fp(
  input_table=mc_ann_file,
  mc_object = mc,
  mat_object = mat
)
scdb_add_mc(id="ct_polyp",mc_ct)
```

Thank you!

Betty
