### ISSUE TITLE
Can not find ../annotations/pairs_cnidaria_closeparalogs-nr_2020-10-23.csv

### ISSUE THREAD

**Issue by zrhhl** [sebepedroslab/Stylophora_single_cell_atlas#2]
Thanks for your detailed analysis code! While when I repeat the part "08-Cross_species_comparison", I could not find the "pairs_cnidaria_closeparalogs-nr_2020-10-23.csv" file. The "annotation" folder did not contain it. So maybe it is an intermediate file or download from a database? Look forward to your reply. Thanks! :wink:

Best,
Laura

**Comment by anamariaelek** [comment]
Hi Laura, the file was accidentally hidden by `.gitignore`, thanks for pointing it out, fixed now.

**Comment by zrhhl** [comment]
> Hi Laura, the file was accidentally hidden by `.gitignore`, thanks for pointing it out, fixed now.

Thanks! :smiling_face_with_three_hearts:

Best,
Laura
