### ISSUE TITLE
Missing file “umi.tab/CORAL0001.txt”

### ISSUE THREAD

**Issue by zrhhl** [sebepedroslab/Stylophora_single_cell_atlas#3]
Hi, I have met another question when I run the code from "01_Metacell_coral.Rmd" :
`# import UMI table
mat_nm <- "coral"
mcell_import_multi_mars(
  mat_nm = mat_nm,
  dataset_table_fn = file.path(cluster_dir, "MARS_Batches_coral.txt"),
  base_dir = "umi.tab",
  force = TRUE
)`

It returned 
`File 'umi.tab/CORAL0001.txt' does not exist or is non-readable.`

I have checked the raw data and processed data, but I couldn't find the related files. The way to input matrix puzzled me. Hope for your help. Thanks! :eyes:

Best,
Laura

**Comment by anamariaelek** [comment]
[`mcell_import_multi_mars()`](https://rdrr.io/github/tanaylab/metacell/man/mcell_import_multi_mars.html) imports raw counts from MARS-seq, which are too large to be uploaded in the original uncompressed text format.

Instead, you can find the compressed raw cell counts in GEO [GSE166901](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE166901) (`GSE166901_Stylophora_adult_sc_matrix.tar.gz`) as well as in [Mendeley Data](https://data.mendeley.com/datasets/g2mysjfp52/1) (`Spis_adult_sc_UMI_counts.RDS`), or download the filtered final version of it from the [shiny app](https://sebe-lab.shinyapps.io/Stylophora_cell_atlas/).

A matrix in text format can then be loaded to metacell object using [`mcell_import_scmat_tsv()`](https://tanaylab.github.io/metacell/reference/mcell_import_scmat_tsv.html), and in RDS format using [`scmat_read_scmat_10x_custom()`](https://tanaylab.github.io/metacell/reference/scmat_read_scmat_10x_custom.html).

Hope this helps you,
Anamaria

**Comment by zrhhl** [comment]
Ok, I will have a try.
Thank you very much! :wink:

Best,
Laura
