### ISSUE TITLE
data structure of  metacell object("gMCCov" class ) 

### ISSUE THREAD

**Issue by zrhhl** [sebepedroslab/Stylophora_single_cell_atlas#4]
Hi Anamaria,
 
I want to ask another question if it's no trouble.
 
The code in "01_Metacell_coral. Rmd" from line971 write:
```
mc_ct <- sca_cell_type_fp(
  input_table = ann_file,
  mc_object = mc,
  mat_object = mat
) 
```
I have read the code of sca_cell_type_fp()  in Downstream_functions.R.  I felt puzzled by the second parameter, the explanation was "mc_object loaded metacell object (`gMCCov` class)". I am not sure about the data structure of the metacell object and would you please tell me about it? 
 
Thank you so much!

**Comment by anamariaelek** [comment]
Hi Laura,

[`tgMCCov`](https://tanaylab.github.io/metacell/reference/tgMCCov-class.html) (a typo in the documentation) is the main class of the metacell package, representing a metacell clustetring solution. The object `mc` of this class contains several slot, most importantly a gene x metacell matrix of gene expression fold changes in metacells (`mc@mc_fp`) and a vector of single cell metacell memberships (`mc@mc`).

**Comment by zrhhl** [comment]
Thanks for your reply!

Best,
Laura
