### ISSUE TITLE
question about genome data

### ISSUE THREAD

**Issue by huawen-poppy** [sebepedroslab/Stylophora_single_cell_atlas#7]
Hello! Thanks for the nice paper!

In the paper, there is a sentence stating that: We used the NCBI S. pistillata gene annotation (GCA_002571385.1), but added gene models from a previous annotation not overlapping with NCBI genes.

I am wondering could you please teach me how to do that or provide the final genome file you used?

Thank you for your help in advance!

**Comment by anamariaelek** [comment]
Hi, you can find the gene models we used in `Spis_mars_gene_intervals.txt.gz` file in the [mendeley data repository](https://data.mendeley.com/datasets/g2mysjfp52/3) indicated in the paper.

**Comment by huawen-poppy** [comment]
Thank you for getting back to me. I checked the repository and found the file you mentioned. If I understand correctly, the Spis_mars_gene_intervals.txt.gz file is the new annotation file for the NCBI genome fasta file (GCA_002571385.1) of Stylophora, right?

**Comment by anamariaelek** [comment]
Yes, those are the gene intervals we used, extended as described in the paper.

**Comment by huawen-poppy** [comment]
I see. Thank you very much!
